- src/logdata/include/data/logdataworkerthread.h
- src/logdata/src/logdataworkerthread.cpp
Quick fix for now, but need to rework indexing state to use strong types
> Use LineOffset type to fix #39

- src/ui/src/quickfindwidget.cpp
Just fix layout of quikfindwidget.
> fix quikfindwidget layout

- src/ui/src/mainwindow.cpp
Drag&drop and the command line already support opening more than one
file at once, also support it from the file open dialog.
> Allow opening more than one file from the menu

- src/ui/include/crawlerwidget.h
- src/ui/src/crawlerwidget.cpp
I think this would work as a base for fixing  issue #203
> Added 'Clear All Items' in search box

- src/ui/include/predefinedfilters.h
- src/ui/include/predefinedfiltersdialog.h
- src/ui/include/predefinedfiltersdialog.ui
- src/ui/src/predefinedfilters.cpp
- src/ui/src/predefinedfiltersdialog.cpp
One of the features discussed in:
https://github.com/variar/klogg/issues/243
> Add import/export feature to predefined filters

- 3rdparty/roaring/include/roaring.hh
- src/logdata/include/data/compressedlinestorage.h
- src/logdata/include/data/linepositionarray.h
- src/logdata/include/data/linetypes.h
- src/logdata/include/data/logfiltereddataworker.h
- src/logdata/src/compressedlinestorage.cpp
- src/logdata/src/logdataworker.cpp
- src/logdata/src/logfiltereddata.cpp
- src/logdata/src/logfiltereddataworker.cpp
- src/ui/include/abstractlogview.h
- src/ui/include/overview.h
- src/ui/include/overviewwidget.h
- src/ui/include/quickfind.h
- src/ui/include/session.h
- src/ui/src/abstractlogview.cpp
- src/ui/src/crawlerwidget.cpp
- src/ui/src/mainwindow.cpp
- src/ui/src/optionsdialog.cpp
- src/ui/src/overview.cpp
- src/ui/src/overviewwidget.cpp
- src/ui/src/quickfind.cpp
- src/ui/src/session.cpp
- src/utils/include/configuration.h
- src/utils/include/log.h
- src/utils/src/configuration.cpp
This is WIP. Indexing and searching works, but some places where Qt
requires to use int numbers (scrollbars, spinboxes etc.) are buggy.
> feature: allow files with more than 2147483647 lines (#339)

- src/app/cli.h
- src/app/kloggapp.h
- src/filewatch/src/filewatcher.cpp
- src/logging/src/logger.cpp
- src/settings/src/configuration.cpp
- src/ui/src/abstractlogview.cpp
- src/ui/src/crawlerwidget.cpp
- src/ui/src/iconloader.cpp
- src/ui/src/tabbedcrawlerwidget.cpp
@variar, review my changes. I think you will like these minor changes.
> Code refactor and minor optimize codegeneration compiler

- src/ui/src/highlightersdialog.cpp
- src/ui/src/predefinedfiltersdialog.cpp
> fix: append extension to export file if not present

- src/ui/include/abstractlogview.h
- src/ui/src/abstractlogview.cpp
> feat: Add option to save only selected lines to file (#236)

- 3rdparty/CMakeLists.txt
The latest simdutf includes various security and performance improvements.
> Update simdutf version

- src/settings/include/shortcuts.h
- src/settings/src/shortcuts.cpp
- src/ui/include/abstractlogview.h
- src/ui/src/abstractlogview.cpp
> feat: Multiple line selection via shortcuts Ctrl+Up, Ctrl+Down (#441)

- src/ui/include/abstractlogview.h
- src/ui/include/crawlerwidget.h
- src/ui/include/mainwindow.h
- src/ui/include/selection.h
- src/ui/src/abstractlogview.cpp
- src/ui/src/crawlerwidget.cpp
- src/ui/src/mainwindow.cpp
- src/ui/src/selection.cpp
Related to #416.
I noticed `newSelection` and `updateLineNumber` signals in the class AbstractLogView are quite similar. I removed one of them and connected all his slots to another one.
I've attached a gif:
> Feature request: count and show number of selected lines or characters #416

- BUILD.md
It looks like after #558 it also require to install the QtTools package
> docs: update BUILD.md after #558

- src/ui/include/displayfilepath.h
- src/ui/src/displayfilepath.cpp
- src/ui/src/favoritefiles.cpp
- src/ui/src/mainwindow.cpp
Another comparator functor is more difficult to rewrite because the call is in different class methods and files.
> refactor: modernize old functors to lambda expression C++11

- src/logdata/src/logdata.cpp
- src/logdata/src/logfiltereddataworker.cpp
- src/regex/src/regularexpression.cpp
- src/ui/src/abstractlogview.cpp
- src/ui/src/highlighterset.cpp
- src/utils/src/cpu_info.cpp
@variar,
You may have forgotten to add reserve before using `emplace_back`, because it works almost the same as `push_back`.
> fix: optimize `emplace_back()` using `reserve()`

- src/ui/src/abstractlogview.cpp
- src/ui/src/mainwindow.cpp
- src/ui/src/predefinedfilters.cpp
I have also checked `insert()` methods and there is a place where reserve can be used.
> fix: optimize push_back and insert using reserve

- src/ui/include/optionsdialog.h
- src/ui/include/optionsdialog.ui
- src/ui/src/optionsdialog.cpp
> feat: Add a button to restore default shortcuts settings (#578)

- src/logdata/src/logdata.cpp
- src/ui/src/abstractlogview.cpp
Fix some build errors and warnings in src/ui/src/abstractlogview.cpp
> build: fix some build errors and warnings

- src/ui/src/abstractlogview.cpp
Related issues https://github.com/variar/klogg/issues/622
The reason for the crash is the same as #623
> fix: horizontal scrolling display error and crash(#622)

- src/ui/src/crawlerwidget.cpp
Fix bug https://github.com/variar/klogg/issues/630
> fix: doesn't show marks when switching to another filtered view tab

- src/ui/src/crawlerwidget.cpp
Fix the crash issue https://github.com/variar/klogg/issues/628
> fix: crash on exit when there is an opened filtered view tab

- src/ui/src/optionsdialog.cpp
Related links https://doc.qt.io/qt-5/qkeysequence.html#toString
> fix: shortcut key display error on mac

- src/settings/include/shortcuts.h
- src/settings/src/shortcuts.cpp
- src/ui/src/crawlerwidget.cpp
Add shortcuts for crawler toggle buttons.
> feat: Add shortcuts for crawler toggle buttons

- src/settings/include/shortcuts.h
- src/settings/src/shortcuts.cpp
- src/ui/src/mainwindow.cpp
- src/ui/src/optionsdialog.cpp
- To make it easier to add shortcuts without missing parameters, change the default storage structure for shortcuts
- Add new shortcut options: full screen, maximise/smallen window, preferences
> feat: Add some shortcut
