src/ui/include/mainwindow.h, src/ui/src/mainwindow.cpp
(from Kuba15@731e4d2, adapted to klogg)
It's been sitting at nickbnf/glogg#51 without any progress, but the file structure has changed between glogg and klogg, so I manually added it here.
=> Add 'Follow file' checkbox in panel

CMakeLists.txt
CMake 3.10 is used in the current Ubuntu LTS and compatibility only requires a small change.
=> CMake 3.10 compat

src/ui/src/abstractlogview.cpp
The documentation for [KeyEvent::text()](https://doc.qt.io/qt-5/qkeyevent.html#text) states "could return an empty string" - and it did on my system for the arrow keys.
=> Prevent potential out-of-bounds access in AbstractLogView::keyPressEvent

src/ui/src/crawlerwidget.cpp
I've had some colleagues ask what that UI-element is for, since it's not very descriptive if empty.
So I thought I'd just hide it if it has nothing to tell.
=> Hide searchInfoLine if empty

src/logdata/include/data/linetypes.h, src/logdata/include/data/logfiltereddata.h, src/logdata/include/data/logfiltereddataworkerthread.h, src/logdata/include/data/marks.h, src/logdata/src/logfiltereddata.cpp, src/logdata/src/logfiltereddataworkerthread.cpp, src/logdata/src/marks.cpp, tests/logfiltereddataTest.cpp
As promised in #37, here's the rebased work.
For some reason I also need to apply the following patch, otherwise my `item` is corrupted. I think this occurs sometimes when adding marks. While this does fix it, I don't see why the previous code would be wrong. Maybe it's just something else on my setup triggering the failure, so I didn't include it.
Make sure to play with the cache a little! Well, I'm sure you will anyways, to evaluate if you want this change or not.
```
diff --git a/src/logdata/include/data/logfiltereddata.h b/src/logdata/include/data/logfiltereddata.h
index b66489b..d529f74 100644
--- a/src/logdata/include/data/logfiltereddata.h
+++ b/src/logdata/include/data/logfiltereddata.h
@@ -220,8 +220,8 @@ class LogFilteredData : public AbstractLogData {
void …
```
=> Eagerly fill marks and matches cache

src/app/main.cpp
Below are screenshots of resulting changes.
Original `Highlighters` dialog on my 4K display looked like this:
After proposed commit it looks like this:
Also notice left bar with Marks and line numbers; TabBar vertical size etc:
=> Improve Hidpi displays support

BUILD.md, README.md
* Extract the build instructions to its own-focused file.
* Add a link to the doc/documentation.rst file in the Overview and Help
sections.
* Fix minor typos.
=> README: extract BUILD.md, add doc link, fix typos

BUILD.md, README.md
Adjust markdown headings to comply with Codacy doc standards.
=> README.md, BUILD.md: adjust heading levels

src/ui/src/abstractlogview.cpp
Fix for a bug where double click on an empty line in the filtered view caused an assert.
=> Fixed assert when double clicking on empty line in filtered view

src/ui/src/optionsdialog.cpp
Noticed that the font size combo box was empty and that font size wasn't saved.
=> Fix font size dialog

src/ui/CMakeLists.txt, src/ui/include/crawlerwidget.h, src/ui/include/mainwindow.h, src/ui/include/predefinedfilters.h, src/ui/include/predefinedfiltersdialog.h, src/ui/include/predefinedfiltersdialog.ui, src/ui/src/crawlerwidget.cpp, src/ui/src/mainwindow.cpp, src/ui/src/predefinedfilters.cpp, src/ui/src/predefinedfiltersdialog.cpp
This implements issue discussed in: https://github.com/variar/klogg/issues/191.
New drop-down menu located next to "auto-refresh" button is introduced and it includes configurable filters which are automatically entered into search field.
To enable filter configuration new dialog was added in Tools -> Configure predefined filters.
=> Add drop-down menu with predefined filters

DOCUMENTATION.md
Just adding a note about the .conf file extension for exported files.  
Thanks again!
=> docs: Update DOCUMENTATION.md to call out extension on exporting configs

src/ui/src/predefinedfiltersdialog.cpp
- ensure file extension **conf** is added when user didn't type it while exporting predefined filters.
=> Export filters fix file extension

src/ui/include/crawlerwidget.h, src/ui/include/predefinedfilterscombobox.h, src/ui/src/crawlerwidget.cpp, src/ui/src/predefinedfilterscombobox.cpp
User input from search line field is reflected in Predefined Filters menu, i. e. any predefined filter is marked as checked if it is a part of user input from the search line field.
=> Reflect search field on check-boxes in Predefined Filters

src/settings/include/configuration.h, src/ui/include/mainwindow.h, src/ui/include/optionsdialog.ui, src/ui/include/recentfiles.h, src/ui/src/mainwindow.cpp, src/ui/src/optionsdialog.cpp, src/ui/src/recentfiles.cpp
Changes:
- move the list of recent files to a dedicated submenu
- added an option to configure the number of recent files to list
- added option to clean up the recent files list
=> Move recent files to a separate submenu

src/ui/src/abstractlogview.cpp
I accidentally deleted one shortcut in the PR #542. I'm sorry. Please fix it
=> fix: return deleted shortcut ReplaceSearch

src/settings/src/shortcuts.cpp
When I translated the file, I found that the newly added shortcut did not have an action name, so I added.
- **before modification**:
- **after modification**:
=> Shortcuts “Select lines up/down” No action name

src/app/i18n/en.ts, src/app/i18n/zh-CN.ts, src/ui/include/optionsdialog.h, src/ui/src/optionsdialog.cpp
related to #348
I've implemented in that way, if a duplicate is found, conflicting cells are highlighted red and Apply and OK buttons are disabled
=> feat: add a check for duplicate shortcuts to shortcut editor (348)

src/ui/src/tabbedcrawlerwidget.cpp
**Problem**
After opening a new file, the first tab doesn't show.
**Fix**
=> fix: the first tab doesn't show when a new file is opened

src/ui/src/abstractlogview.cpp
Fix the last line being covered in follow mode when filelines*charHeight is the screen height
=> fix: The last line being covered in follow mode(#117)

src/logdata/include/logfiltereddata.h, src/logdata/src/logfiltereddata.cpp, src/ui/include/filteredview.h, src/ui/src/crawlerwidget.cpp, src/ui/src/filteredview.cpp
Issue:
https://github.com/variar/klogg/issues/603
When in the "Marks" tab, I perform a new search, however, it doesn't switch to the "Marks and matches" tab automatically, I have to switch the tab manually. It's better to switch to the "Marks and matches" tab automatically when starting a new search.
Change:
Switch to the "Marks and matches" tab when starting a new search if the current filtered view is "Marks".
=> feat: switch to 'Marks and matches' view when starting a new search

src/ui/src/optionsdialog.cpp
**Problem 1**
Some action descriptions are not shown completely.
**Problem 2**
The row height is not enough to show the text and button completely.
**Fix**
1. Resize the action column to contents.
2. Don't stretch rows
Windows:
Mac:
=> fix: fix some UI issues in Preference->Shortcuts table

src/ui/src/predefinedfiltersdialog.cpp
**Problem**
The regex checkbox doesn't display completely.
**Fix**
Resize new row to contents.
=> fix: predefined filters table row height is too small

src/ui/src/crawlerwidget.cpp
=> fix: crash when closing search results tab and scrolling till the end of view (#614)

.gitignore, src/ui/src/abstractlogview.cpp
> Note: Until 5.15.1, the behavior was undefined when start < 0, length < 0, or start + length > [size](https://doc.qt.io/qt-5/qstringview.html#size)(). Since 5.15.2, the behavior is compatible with [QString::mid](https://doc.qt.io/qt-5/qstring.html#mid)().
Link to original article：[QStringView::mid](https://doc.qt.io/qt-5/qstringview.html#mid-1)
The second parameter of `QStringView::mid` has undefined behavior before `Qt 5.15.1` and behaves normally in Windows, but there is out-of-bounds access in Linux
Related issues #622
=> fix: view log crash if Qt version < 5.15

src/ui/src/predefinedfilterscombobox.cpp
In the predefined filters drop-down list, the filters are truncated, this PR aims to make the drop-down list wider.
Before:
Now:
=> fix: make predefined filters popup wider

src/ui/src/scratchpad.cpp
=> fix: Scratchpad Format Json does not handle Json arrays(#490)

src/app/i18n/zh_CN.ts
Added some translations and corrected some ones.
**Before**
**After**
Signed-off-by: Junbo Zheng <zhengjunbo1@xiaomi.com>
=> src/app/i18n: update shortcuts translation for chinese

src/ui/src/abstractlogview.cpp
Sometimes I accidentally remove a marked line from the right-click menu. This PR makes a change to show "Unmark" in the right-client menu for the marked line.
Show "Unmark" for the marked line:
Still show "Mark" when there is an unmarked line selected:
=> feat: show unmark in the right-click memu for the marked line

src/settings/include/shortcuts.h, src/settings/src/shortcuts.cpp, src/ui/src/crawlerwidget.cpp, src/ui/src/optionsdialog.cpp
**Problem**
Currently, we can change filtered lines' visibility with the shortcut "Key_V". However, the shortcut can only change the visibility forward, so we have to click Key_V twice to return to the current view.
**Change**
With the changes in this PR, we can change the filtered lines' visibility forward and backward.
- Forward: V
- Backward: Shift+V
_Shortcut preferences:_
=> feat: support changing filtered lines visibility backward

src/ui/src/predefinedfiltersdialog.cpp
**Problem**
The regex checkbox doesn't display completely on Windows. I had a [fix ](https://github.com/variar/klogg/pull/611) for the newly added row, but it can't cover the existing rows.
**Fix**
1. Resize rows to contents
2. Resize the first column to contents
=> fix: predefined filters table row height is too small on Windows

src/ui/include/mainwindow.h, src/ui/src/mainwindow.cpp
feature #416 is implemented in PR #561, 
but commit [refactor: add a separate type for line column, make other line realted types safer](https://github.com/variar/klogg/commit/a31627637236fdaa0ce51ebcb79c6e32f632f331) modifies the argument type of the slot function so that it doesn't work
=> fix: cannot display the number of lines or characters selected(#416)

src/ui/src/crawlerwidget.cpp
- Fix 3/4-bit ANSI can't hide multi-color
- Support hiding 8-bit ANSI colors
- Support hiding 24-bit ANSI colors
Reference Documents：https://en.wikipedia.org/wiki/ANSI_escape_code
=> fix: some ANSI colors cannot be hidden

src/ui/include/crawlerwidget.h, src/ui/include/mainwindow.h, src/ui/src/crawlerwidget.cpp, src/ui/src/mainwindow.cpp
Fix an extra crash issue in https://github.com/variar/klogg/issues/628
This PR not only fixes the crash issue, it also covers the quick search issue in the filtered view tab. Without this change, the "Find next" and "Finx previous" don't work in the filtered view tab.
=> fix: crash on exit when the first empty filtered view tab is closed

src/ui/src/crawlerwidget.cpp
Sorry，I forgot a special case.
Because 0 is a special number, parameters starting with 0 are allowed to omit the separator from subsequent parameters.
The foreground parameter contains 30-37, 90-97 and the background color parameter contains 40-47, 100-107, so there exists a case `\033[0101m RED TEXT\033[0m`
=> fix: ANSI color parameter support without separator

src/ui/include/scratchpad.h, src/ui/src/scratchpad.cpp
The timestamps in the logs belong to different time zones, so add a conversion function
=> feat: Add time zone conversion to time in scratchpad

src/ui/src/abstractlogview.cpp
The previous logic added a pen stroke at the top 3 pixels wide, and 5 pixels at the bottom. Probably because the lower pen stroke is misaligned (too far down) and needs a larger stroke width to compensate for this misalignment, which causes part of that stroke (the lower part) to be cut of by the next line (but not if the selection is on the last line).
This causes different effects both at lines selected in the middle of the log as well as the end of the log (last line) in different ways.
It also re-added pen several times after changing the width of the pen, which is simply unnecessary (and may have added to this effect of increasing color intensity in the original version)
The fix simple removes unnecessary lines of code as well as adjusting the position of the lower stroke and …
=> fix selected single line appearance

src/ui/src/quickfindwidget.cpp
I also think that pressing Enter in quick find should be the same as clicking the Next button.
=> fix: "Enter" closes quick find dialog(#636)

src/ui/src/mainwindow.cpp
Recently files with the same filename could not be distinguished correctly, so a tooltips was added.
=> feat: show tooltips for recent files

README.md
The URL for the ubuntu repository list was incorrect and produced a 404
=> doc: correct Ubuntu .deb url in readme

.clang-format, src/logdata/include/linetypes.h
This PR is to resolve the tab alignment issue in #663, this commit also removes the conflicting configuration from the .clang-format file.
**Before**
**After**
=> fix: untabify function work error(#663)

src/ui/CMakeLists.txt, src/ui/include/abstractlogview.h, src/ui/include/highlighterset.h, src/ui/include/highlightersmenu.h, src/ui/include/mainwindow.h, src/ui/include/menu.h, src/ui/src/abstractlogview.cpp, src/ui/src/crawlerwidget.cpp, src/ui/src/highlightersmenu.cpp, src/ui/src/mainwindow.cpp, src/ui/src/menu.cpp
This pull request is to add a feature(#551). But some bugs were found during development, so I fixed it by the way.
Modify as follows：
- When clicking the action in the highlighters menu, the menu list is not hidden
- Fix the display error of None Action in the highlighters menu
- Fix that the highlighters in the right-click menu only take effect in the current logview
=> trigger the highlisters menu without closing

src/ui/include/predefinedfilterscombobox.h, src/ui/src/abstractlogview.cpp, src/ui/src/predefinedfilterscombobox.cpp
=> fix: fixed memleaks and predefinedfilterscombobox and abstractlogview

src/ui/src/overview.cpp
I noticed that when viewing files, the "view lines" shown on the overview did not line up with the actual lines that were being viewed. Instead, one of the lines would always remain near the top of the file.
This is because [this change](https://github.com/variar/klogg/commit/151a65c08ba772468bba651f05f381e9e34eeb9a) added some extra brackets to `Overview::getViewLines()` that changed the order of operations in the calculation of `bottom`. I've fixed up the order of operations for this calculation.
Original working code:
`bottom = (int)((qint64)top + nbLines_.get() * height_ / linesInFile_.get());`
Code with incorrect order of operations:
`bottom = static_cast<int>( ( static_cast<unsigned>( top ) + nbLines_.get() ) * height_
/ ( linesInFile_.get() ) );`
Fixed code:
`bottom = top + …
=> fix: bottom view line in overview is now calculated correctly.
